
eval_metric: rmse
objective: "reg:squarederror"
nsample: 50
run_name: "xgboost_random_grid"

search_grid:
  booster: ['gbtree','dart']
  lambda: [0.1, 0.01, 0.001]
  alpha: [0.1, 0.01, 0.001]
  max_depth: [2,3,4, 5, 7]
  eta: [0.1, 0.01, 0.001]
  gamma: [0.1, 0.01, 0.001]
  grow_policy: ["depthwise", "lossguide"]
 
  